/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenderNaPlataformaRouteImport } from './routes/vender-na-plataforma'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProdutorRouteImport } from './routes/produtor'
import { Route as PrivateLabelRouteImport } from './routes/private-label'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ClubeRouteImport } from './routes/clube'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoresIndexRouteImport } from './routes/produtores.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ProdutoresSlugRouteImport } from './routes/produtores.$slug'
import { Route as ProdutorProdutosRouteImport } from './routes/produtor.produtos'
import { Route as ProdutorPerfilRouteImport } from './routes/produtor.perfil'
import { Route as ProdutorPedidosRouteImport } from './routes/produtor.pedidos'
import { Route as MinhaContaPrivacidadeRouteImport } from './routes/minha-conta.privacidade'
import { Route as CafeSlugRouteImport } from './routes/cafe.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminVendasRouteImport } from './routes/admin.vendas'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminProdutoresRouteImport } from './routes/admin.produtores'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminIntegracoesRouteImport } from './routes/admin.integracoes'
import { Route as AdminCuponsRouteImport } from './routes/admin.cupons'
import { Route as AdminConteudoRouteImport } from './routes/admin.conteudo'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminCandidaturasRouteImport } from './routes/admin.candidaturas'
import { Route as AdminAssinaturasRouteImport } from './routes/admin.assinaturas'
import { Route as AdminProdutosNovoRouteImport } from './routes/admin.produtos.novo'
import { Route as AdminProdutosIdEditarRouteImport } from './routes/admin.produtos.$id.editar'

const VenderNaPlataformaRoute = VenderNaPlataformaRouteImport.update({
  id: '/vender-na-plataforma',
  path: '/vender-na-plataforma',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutorRoute = ProdutorRouteImport.update({
  id: '/produtor',
  path: '/produtor',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLabelRoute = PrivateLabelRouteImport.update({
  id: '/private-label',
  path: '/private-label',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubeRoute = ClubeRouteImport.update({
  id: '/clube',
  path: '/clube',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoresIndexRoute = ProdutoresIndexRouteImport.update({
  id: '/produtores/',
  path: '/produtores/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoresSlugRoute = ProdutoresSlugRouteImport.update({
  id: '/produtores/$slug',
  path: '/produtores/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutorProdutosRoute = ProdutorProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => ProdutorRoute,
} as any)
const ProdutorPerfilRoute = ProdutorPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ProdutorRoute,
} as any)
const ProdutorPedidosRoute = ProdutorPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => ProdutorRoute,
} as any)
const MinhaContaPrivacidadeRoute = MinhaContaPrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => MinhaContaRoute,
} as any)
const CafeSlugRoute = CafeSlugRouteImport.update({
  id: '/cafe/$slug',
  path: '/cafe/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendasRoute = AdminVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutoresRoute = AdminProdutoresRouteImport.update({
  id: '/produtores',
  path: '/produtores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegracoesRoute = AdminIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoRoute = AdminConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCandidaturasRoute = AdminCandidaturasRouteImport.update({
  id: '/candidaturas',
  path: '/candidaturas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssinaturasRoute = AdminAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosNovoRoute = AdminProdutosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminProdutosRoute,
} as any)
const AdminProdutosIdEditarRoute = AdminProdutosIdEditarRouteImport.update({
  id: '/$id/editar',
  path: '/$id/editar',
  getParentRoute: () => AdminProdutosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assinatura': typeof AssinaturaRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/clube': typeof ClubeRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/private-label': typeof PrivateLabelRoute
  '/produtor': typeof ProdutorRouteWithChildren
  '/quiz': typeof QuizRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/vender-na-plataforma': typeof VenderNaPlataformaRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/candidaturas': typeof AdminCandidaturasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtores': typeof AdminProdutoresRoute
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/admin/vendas': typeof AdminVendasRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cafe/$slug': typeof CafeSlugRoute
  '/minha-conta/privacidade': typeof MinhaContaPrivacidadeRoute
  '/produtor/pedidos': typeof ProdutorPedidosRoute
  '/produtor/perfil': typeof ProdutorPerfilRoute
  '/produtor/produtos': typeof ProdutorProdutosRoute
  '/produtores/$slug': typeof ProdutoresSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/produtores/': typeof ProdutoresIndexRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/produtos/$id/editar': typeof AdminProdutosIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assinatura': typeof AssinaturaRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/clube': typeof ClubeRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/private-label': typeof PrivateLabelRoute
  '/produtor': typeof ProdutorRouteWithChildren
  '/quiz': typeof QuizRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/vender-na-plataforma': typeof VenderNaPlataformaRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/candidaturas': typeof AdminCandidaturasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtores': typeof AdminProdutoresRoute
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/admin/vendas': typeof AdminVendasRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cafe/$slug': typeof CafeSlugRoute
  '/minha-conta/privacidade': typeof MinhaContaPrivacidadeRoute
  '/produtor/pedidos': typeof ProdutorPedidosRoute
  '/produtor/perfil': typeof ProdutorPerfilRoute
  '/produtor/produtos': typeof ProdutorProdutosRoute
  '/produtores/$slug': typeof ProdutoresSlugRoute
  '/blog': typeof BlogIndexRoute
  '/produtores': typeof ProdutoresIndexRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/produtos/$id/editar': typeof AdminProdutosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assinatura': typeof AssinaturaRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/clube': typeof ClubeRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/private-label': typeof PrivateLabelRoute
  '/produtor': typeof ProdutorRouteWithChildren
  '/quiz': typeof QuizRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/vender-na-plataforma': typeof VenderNaPlataformaRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/candidaturas': typeof AdminCandidaturasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtores': typeof AdminProdutoresRoute
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/admin/vendas': typeof AdminVendasRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cafe/$slug': typeof CafeSlugRoute
  '/minha-conta/privacidade': typeof MinhaContaPrivacidadeRoute
  '/produtor/pedidos': typeof ProdutorPedidosRoute
  '/produtor/perfil': typeof ProdutorPerfilRoute
  '/produtor/produtos': typeof ProdutorProdutosRoute
  '/produtores/$slug': typeof ProdutoresSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/produtores/': typeof ProdutoresIndexRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/produtos/$id/editar': typeof AdminProdutosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assinatura'
    | '/cadastro'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/clube'
    | '/contato'
    | '/login'
    | '/minha-conta'
    | '/privacidade'
    | '/private-label'
    | '/produtor'
    | '/quiz'
    | '/recuperar-senha'
    | '/reset-password'
    | '/sobre'
    | '/termos'
    | '/vender-na-plataforma'
    | '/admin/assinaturas'
    | '/admin/candidaturas'
    | '/admin/clientes'
    | '/admin/config'
    | '/admin/conteudo'
    | '/admin/cupons'
    | '/admin/integracoes'
    | '/admin/leads'
    | '/admin/pedidos'
    | '/admin/produtores'
    | '/admin/produtos'
    | '/admin/vendas'
    | '/blog/$slug'
    | '/cafe/$slug'
    | '/minha-conta/privacidade'
    | '/produtor/pedidos'
    | '/produtor/perfil'
    | '/produtor/produtos'
    | '/produtores/$slug'
    | '/blog/'
    | '/produtores/'
    | '/admin/produtos/novo'
    | '/admin/produtos/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assinatura'
    | '/cadastro'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/clube'
    | '/contato'
    | '/login'
    | '/minha-conta'
    | '/privacidade'
    | '/private-label'
    | '/produtor'
    | '/quiz'
    | '/recuperar-senha'
    | '/reset-password'
    | '/sobre'
    | '/termos'
    | '/vender-na-plataforma'
    | '/admin/assinaturas'
    | '/admin/candidaturas'
    | '/admin/clientes'
    | '/admin/config'
    | '/admin/conteudo'
    | '/admin/cupons'
    | '/admin/integracoes'
    | '/admin/leads'
    | '/admin/pedidos'
    | '/admin/produtores'
    | '/admin/produtos'
    | '/admin/vendas'
    | '/blog/$slug'
    | '/cafe/$slug'
    | '/minha-conta/privacidade'
    | '/produtor/pedidos'
    | '/produtor/perfil'
    | '/produtor/produtos'
    | '/produtores/$slug'
    | '/blog'
    | '/produtores'
    | '/admin/produtos/novo'
    | '/admin/produtos/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assinatura'
    | '/cadastro'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/clube'
    | '/contato'
    | '/login'
    | '/minha-conta'
    | '/privacidade'
    | '/private-label'
    | '/produtor'
    | '/quiz'
    | '/recuperar-senha'
    | '/reset-password'
    | '/sobre'
    | '/termos'
    | '/vender-na-plataforma'
    | '/admin/assinaturas'
    | '/admin/candidaturas'
    | '/admin/clientes'
    | '/admin/config'
    | '/admin/conteudo'
    | '/admin/cupons'
    | '/admin/integracoes'
    | '/admin/leads'
    | '/admin/pedidos'
    | '/admin/produtores'
    | '/admin/produtos'
    | '/admin/vendas'
    | '/blog/$slug'
    | '/cafe/$slug'
    | '/minha-conta/privacidade'
    | '/produtor/pedidos'
    | '/produtor/perfil'
    | '/produtor/produtos'
    | '/produtores/$slug'
    | '/blog/'
    | '/produtores/'
    | '/admin/produtos/novo'
    | '/admin/produtos/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssinaturaRoute: typeof AssinaturaRoute
  CadastroRoute: typeof CadastroRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRoute
  ClubeRoute: typeof ClubeRoute
  ContatoRoute: typeof ContatoRoute
  LoginRoute: typeof LoginRoute
  MinhaContaRoute: typeof MinhaContaRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  PrivateLabelRoute: typeof PrivateLabelRoute
  ProdutorRoute: typeof ProdutorRouteWithChildren
  QuizRoute: typeof QuizRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  VenderNaPlataformaRoute: typeof VenderNaPlataformaRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CafeSlugRoute: typeof CafeSlugRoute
  ProdutoresSlugRoute: typeof ProdutoresSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProdutoresIndexRoute: typeof ProdutoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vender-na-plataforma': {
      id: '/vender-na-plataforma'
      path: '/vender-na-plataforma'
      fullPath: '/vender-na-plataforma'
      preLoaderRoute: typeof VenderNaPlataformaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtor': {
      id: '/produtor'
      path: '/produtor'
      fullPath: '/produtor'
      preLoaderRoute: typeof ProdutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-label': {
      id: '/private-label'
      path: '/private-label'
      fullPath: '/private-label'
      preLoaderRoute: typeof PrivateLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clube': {
      id: '/clube'
      path: '/clube'
      fullPath: '/clube'
      preLoaderRoute: typeof ClubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtores/': {
      id: '/produtores/'
      path: '/produtores'
      fullPath: '/produtores/'
      preLoaderRoute: typeof ProdutoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtores/$slug': {
      id: '/produtores/$slug'
      path: '/produtores/$slug'
      fullPath: '/produtores/$slug'
      preLoaderRoute: typeof ProdutoresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtor/produtos': {
      id: '/produtor/produtos'
      path: '/produtos'
      fullPath: '/produtor/produtos'
      preLoaderRoute: typeof ProdutorProdutosRouteImport
      parentRoute: typeof ProdutorRoute
    }
    '/produtor/perfil': {
      id: '/produtor/perfil'
      path: '/perfil'
      fullPath: '/produtor/perfil'
      preLoaderRoute: typeof ProdutorPerfilRouteImport
      parentRoute: typeof ProdutorRoute
    }
    '/produtor/pedidos': {
      id: '/produtor/pedidos'
      path: '/pedidos'
      fullPath: '/produtor/pedidos'
      preLoaderRoute: typeof ProdutorPedidosRouteImport
      parentRoute: typeof ProdutorRoute
    }
    '/minha-conta/privacidade': {
      id: '/minha-conta/privacidade'
      path: '/privacidade'
      fullPath: '/minha-conta/privacidade'
      preLoaderRoute: typeof MinhaContaPrivacidadeRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/cafe/$slug': {
      id: '/cafe/$slug'
      path: '/cafe/$slug'
      fullPath: '/cafe/$slug'
      preLoaderRoute: typeof CafeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendas': {
      id: '/admin/vendas'
      path: '/vendas'
      fullPath: '/admin/vendas'
      preLoaderRoute: typeof AdminVendasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtores': {
      id: '/admin/produtores'
      path: '/produtores'
      fullPath: '/admin/produtores'
      preLoaderRoute: typeof AdminProdutoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integracoes': {
      id: '/admin/integracoes'
      path: '/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AdminIntegracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo': {
      id: '/admin/conteudo'
      path: '/conteudo'
      fullPath: '/admin/conteudo'
      preLoaderRoute: typeof AdminConteudoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/candidaturas': {
      id: '/admin/candidaturas'
      path: '/candidaturas'
      fullPath: '/admin/candidaturas'
      preLoaderRoute: typeof AdminCandidaturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assinaturas': {
      id: '/admin/assinaturas'
      path: '/assinaturas'
      fullPath: '/admin/assinaturas'
      preLoaderRoute: typeof AdminAssinaturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos/novo': {
      id: '/admin/produtos/novo'
      path: '/novo'
      fullPath: '/admin/produtos/novo'
      preLoaderRoute: typeof AdminProdutosNovoRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
    '/admin/produtos/$id/editar': {
      id: '/admin/produtos/$id/editar'
      path: '/$id/editar'
      fullPath: '/admin/produtos/$id/editar'
      preLoaderRoute: typeof AdminProdutosIdEditarRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
  }
}

interface AdminProdutosRouteChildren {
  AdminProdutosNovoRoute: typeof AdminProdutosNovoRoute
  AdminProdutosIdEditarRoute: typeof AdminProdutosIdEditarRoute
}

const AdminProdutosRouteChildren: AdminProdutosRouteChildren = {
  AdminProdutosNovoRoute: AdminProdutosNovoRoute,
  AdminProdutosIdEditarRoute: AdminProdutosIdEditarRoute,
}

const AdminProdutosRouteWithChildren = AdminProdutosRoute._addFileChildren(
  AdminProdutosRouteChildren,
)

interface AdminRouteChildren {
  AdminAssinaturasRoute: typeof AdminAssinaturasRoute
  AdminCandidaturasRoute: typeof AdminCandidaturasRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminConteudoRoute: typeof AdminConteudoRoute
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminIntegracoesRoute: typeof AdminIntegracoesRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutoresRoute: typeof AdminProdutoresRoute
  AdminProdutosRoute: typeof AdminProdutosRouteWithChildren
  AdminVendasRoute: typeof AdminVendasRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssinaturasRoute: AdminAssinaturasRoute,
  AdminCandidaturasRoute: AdminCandidaturasRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminConteudoRoute: AdminConteudoRoute,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminIntegracoesRoute: AdminIntegracoesRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutoresRoute: AdminProdutoresRoute,
  AdminProdutosRoute: AdminProdutosRouteWithChildren,
  AdminVendasRoute: AdminVendasRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MinhaContaRouteChildren {
  MinhaContaPrivacidadeRoute: typeof MinhaContaPrivacidadeRoute
}

const MinhaContaRouteChildren: MinhaContaRouteChildren = {
  MinhaContaPrivacidadeRoute: MinhaContaPrivacidadeRoute,
}

const MinhaContaRouteWithChildren = MinhaContaRoute._addFileChildren(
  MinhaContaRouteChildren,
)

interface ProdutorRouteChildren {
  ProdutorPedidosRoute: typeof ProdutorPedidosRoute
  ProdutorPerfilRoute: typeof ProdutorPerfilRoute
  ProdutorProdutosRoute: typeof ProdutorProdutosRoute
}

const ProdutorRouteChildren: ProdutorRouteChildren = {
  ProdutorPedidosRoute: ProdutorPedidosRoute,
  ProdutorPerfilRoute: ProdutorPerfilRoute,
  ProdutorProdutosRoute: ProdutorProdutosRoute,
}

const ProdutorRouteWithChildren = ProdutorRoute._addFileChildren(
  ProdutorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AssinaturaRoute: AssinaturaRoute,
  CadastroRoute: CadastroRoute,
  CarrinhoRoute: CarrinhoRoute,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRoute,
  ClubeRoute: ClubeRoute,
  ContatoRoute: ContatoRoute,
  LoginRoute: LoginRoute,
  MinhaContaRoute: MinhaContaRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  PrivateLabelRoute: PrivateLabelRoute,
  ProdutorRoute: ProdutorRouteWithChildren,
  QuizRoute: QuizRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  VenderNaPlataformaRoute: VenderNaPlataformaRoute,
  BlogSlugRoute: BlogSlugRoute,
  CafeSlugRoute: CafeSlugRoute,
  ProdutoresSlugRoute: ProdutoresSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProdutoresIndexRoute: ProdutoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
